version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: travel-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: knightagentsumit123/travel-backend:latest
    container_name: travel-backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/travel-journal
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: knightagentsumit123/travel-frontend:latest
    container_name: travel-frontend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
